server:
  port: 8080
spring:
  application:
    name: restaurant-service
spec:
  selector:
    app: restaurant-service   
  data:
    mongodb:
      authentication-database: admin
      username: monogoDB
      password: VEER2019
      database: restaurant_db
      port: 27017
      host: mongodb-persistent-rxprm-credentials-4bjp7
